### ISSUE TITLE
Regarding classification task 

### ISSUE THREAD

**Issue by connectedhealthcaremy** [stefanonardo/pytorch-esn#2]
we have run the code and we have put the features in tensor object  for classification but we are getting following exception AttributeError: 'int' object has no attribute 'dim' can you help in elobrating us why this exception is coming The below are the lines at which it was coming 
    if input.dim() == 2 and bias is not None:
        # fused op is marginally faster

**Comment by connectedhealthcaremy** [comment]
how to define hidden we have randomly selected the hidden but its becoming zero when computing the output please help us to resolve this issue for classificattion

**Comment by connectedhealthcaremy** [comment]
All the remaining issues resolved code running succcessfully but the output we are getting for classification is just single vector. Do we need to give target in the form of (1,0)(0,1) or singlevector (0,1,1,0)

**Comment by stefanonardo** [comment]
It depends on your loss function. I added two examples to the repository. You should take a look to `mnist.py` classification task.
