### ISSUE TITLE
Problems with mackey example

### ISSUE THREAD

**Issue by DaddyWesker** [stefanonardo/pytorch-esn#5]
Here is what i've found:
1. 
```
if dtype == torch.double:
    data = np.loadtxt('../../datasets/mg17.csv', delimiter=',', dtype=np.float64)
elif dtype == torch.float:
data = np.loadtxt('../../datasets/mg17.csv', delimiter=',', dtype=np.float32)
```
Here are wrong pathes to dataset since it's in the same directory so it should be 
```
if dtype == torch.double:
    data = np.loadtxt('datasets/mg17.csv', delimiter=',', dtype=np.float64)
elif dtype == torch.float:
    data = np.loadtxt('datasets/mg17.csv', delimiter=',', dtype=np.float32)
```
2. Next.
```
X_data = np.expand_dims(data[:, [0]], axis=1)
Y_data = np.expand_dims(data[:, [1]], axis=1)
```
I guess it should be 
```
X_data = np.expand_dims(data[:, [1]], axis=1)
Y_data = np.expand_dims(data[:, [0]], axis=1)
```
or am i wrong?
3. When launching with these fixes i'm getting 

> Training error: 0.051316608186617714
> Test error: 0.052949286276803606

It's quite big. Moreover, when i'm trying to make plot to compare real and output i'm getting following picture on "test" data

5000 test outputs
![5000_outputs](https://user-images.githubusercontent.com/10774222/46863583-862a6200-ce20-11e8-9723-21c994f79844.png)

Closer look (100 outputs)
![100_outputs closer_look](https://user-images.githubusercontent.com/10774222/46863581-862a6200-ce20-11e8-8ee9-542689192ebb.png)

Am i doing something wrong?

**Comment by CICS-Oleg** [comment]
I've faced the very same problems.

**Comment by DaddyWesker** [comment]
> No, first version is ok. Take a look at the file. The second column is one step ahead the first. Why would you change it?
Well, in file mg17.csv it can be seen that first column is some numbers different to each other. Second column is all consists of same numbers all over again "1.236445196138708791e-01". You are sending these 1.236445196138708791e-01 to Y, then sending it to your model and getting just the same result in the output "1.236445196138708791e-01". So it was obvious to me that it's somehow wrong. What the point to send array of "1.236445196138708791e-01" to model getting same "1.236445196138708791e-01" array as output and getting 0 error? So i thought that second column is delta X and first column is Y. And because of that i've changed those columns. And with that assumption it is possible to get graph like green on pictures but not possible to get normal predictions.

**Comment by stefanonardo** [comment]
Ok, I see your point now! The dataset is the problem, second column is wrong. I don't how it happened. I will fix the repo ASAP, in the meantime, try this file: https://gist.github.com/stefanonardo/e216b13b21d07d31ca557058028c1198

**Comment by DaddyWesker** [comment]
> 
> 
> Ok, I see your point now! The dataset is the problem, second column is wrong. I don't how it happened. I will fix the repo ASAP, in the meantime, try this file: https://gist.github.com/stefanonardo/e216b13b21d07d31ca557058028c1198

Great. That worked. Thanks
