### ISSUE TITLE
Error :    TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by JingliangGao** [stefanonardo/pytorch-esn#6]
Hi,
I recently want to predict timeseria data using reservior compute and have refered your code **mackey-glass.py**,.
My pytorch version is '0.4.0' , so some code lines , like "torch.device", "to(device)", have been replaced for version problem. But it still occur an error as follows.
**********************************************************************************************************
Traceback (most recent call last):
  File "mackey-glass.py", line 37, in <module>
    trY_flat = utils.prepare_target(trY.clone(), [trX.size(0)], washout)
  File "/usr/local/lib/python3.5/dist-packages/pytorch_esn-1.2.1-py3.5.egg/torchesn/utils/utilities.py", line 25, in prepare_target
TypeError: 'module' object is not callable
********************************************************************************************************** 
BTW, I have tried to move trX and trY data to CPU/GPU, but it did not work.

It will be helpful if you give me some advices. Thanks :)

**Comment by stefanonardo** [comment]
The error occurs because `torch.tensor()` is only available on 1.0. If you don't want to update PyTorch, try changing `torch.tensor()` to `torch.Tensor()`.

> BTW, I have tried to move trX and trY data to CPU/GPU, but it did not work.
Post your code please.
